### ISSUE TITLE
1주차 온라인 세션을 진행한다 - 3월 8일

### ISSUE THREAD

**Issue by imakerjun** [next-step/blog#149]

**Comment by SEON20** [comment]
title: 책 '마음의 불을'에서 인상 깊은 부분 
description: 이번 글은 1분기 회고입니다. 
category: 책 
link: https://velog.io/@seon21/%EC%B1%85-%EB%A7%88%EC%9D%8C%EC%9D%98-%EB%B6%88%EC%9D%84%EC%97%90%EC%84%9C-%EC%9D%B8%EC%83%81-%EA%B9%8A%EC%9D%80-%EB%B6%80%EB%B6%84

**Comment by SEON20** [comment]
@imakerjun 안녕하세요~^^ 오늘 9:00에 스터디 하는거 어디로 들어가면 될까요?
