### ISSUE TITLE
블랙커피에 중복 등록됩니다.

### ISSUE THREAD

**Issue by loop-study** [next-step/blog#226]
![image](https://user-images.githubusercontent.com/19161176/115190850-99ba9000-a123-11eb-94f5-cf9d6a68a26d.png)

중복 안되게 주의해야할 사항 있는지 궁금합니다.

**Comment by imakerjun** [comment]
@loop-study 
데이터베이스에 이미 PR이 등록된 경우 예외처리하여 중복 등록되지 않게 개선했습니다! 😄
