### ISSUE TITLE
블로그 스터디 소개글 오탈자 제보입니다~

### ISSUE THREAD

**Issue by humblEgo** [next-step/blog#248]
## 오탈자 내용

![image](https://user-images.githubusercontent.com/54612343/116084755-1081fb00-a6d9-11eb-9f11-6d622695628c.png)
- 링크: https://edu.nextstep.camp/c/0riCWbxs/

인용문 내의 작가 이름이 `제임스 서버`인데 괄호 안에는 `Carl Gustav Jung`라고 적혀있습니다.

## 수정 제안

한글 이름과 영문 이름을 '제임스 서버'로 수정 제안 드립니다.

기존 : 제임스 서버(Carl Gustav Jung)
변경 후 : 제임스 서버(James Grover Thurber)

**Comment by imakerjun** [comment]
헉 엄청난 오류가 있었네요 제보해주셔서 감사합니다 🙇🏻
