### ISSUE TITLE
글 목록이 안 보이는 오류

### ISSUE THREAD

**Issue by yujo11** [next-step/blog#292]
![image](https://user-images.githubusercontent.com/61097373/120259296-a8719680-c2ce-11eb-9004-cd6f634a7349.png)

![image](https://user-images.githubusercontent.com/61097373/120259355-c3440b00-c2ce-11eb-8fab-6ac6dd0ff6a3.png)

- 일시 : 2021년 06월 01일 오전 11시 40분
- 이슈 : 사이트 접속시 헤더만 보이고 글 목록이 보이지 않는 이슈
- 접속 URL : https://blackcoffee.blog/

**Comment by loop-study** [comment]
점검하는 줄 알았는데
에러였군요

**Comment by yujo11** [comment]
@loop-study 

앗... 점검중인가요? 

따로 들은게 없어서 이슈로 남겼었는데 점검중이라면 이슈 닫아주심 감사하겠습니다ㅠㅠ

**Comment by loop-study** [comment]
@yujo11 그냥 아무것도 안나와서 점검이라 생각했어요
저도 모릅니다. 😅

**Comment by imakerjun** [comment]
@yujo11 
@loop-study 
관심 가져주셔서 감사합니다! 데이터베이스 migration때문에 잠시 안되었는데 이제 정상화하였습니다 ㅎㅎ
